In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
 import numpy as np

In [3]:
print(np.__version__)

2.3.5


In [4]:
#Creating arrays

In [5]:
list=[1,2,3]
print(list)

[1, 2, 3]


In [9]:
arr_list=np.array(list)
print(arr_list)

[1 2 3]


In [10]:
list2=[4,5,6]

In [15]:
arr_list_2=np.array([list,list2])
print(arr_list_2)

[[1 2 3]
 [4 5 6]]


In [16]:
#numpy array attributes

In [20]:
print("shape",arr_list_2.shape)
print("size",arr_list_2.size)
print("dtype",arr_list_2.dtype)
print("n_dim",arr_list_2.ndim)

shape (2, 3)
size 6
dtype int64
n_dim 2


In [1]:
#CREATING ARRAY 
#1D ARRAY

In [7]:
arr1=np.array([1,2,3])
print(arr1)
print (type(arr1))
print(arr1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [9]:
arr2=np.array([1,2,3,4])
arr2.reshape(1,4)

array([[1, 2, 3, 4]])

In [12]:
#2-d array
arr3=np.array([[1,2,3,4],[3,4,5,6]])
print(arr3)
print (type(arr3))
print(arr3.shape)

[[1 2 3 4]
 [3 4 5 6]]
<class 'numpy.ndarray'>
(2, 4)


In [16]:
##Numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

##Element wise addition
print("Addition:",arr1+arr2)

##Element wise substraction

print("Substraction:",arr1-arr2)
print("Multiplication:",arr1*arr2)
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [22]:
 ##universal function

arr=np.array([1,2,3,4])
print(arr)

#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

##sine
print(np.sin(arr))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [25]:
#array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [36]:
arr[0,0]=100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [39]:
#Standard deviation and mean

data=np.array([1,2,3,4,5])

## mean and Standard deviation

mean=np.mean(data)
std_dev=np.std(data)
print(mean)
print(std_dev)

#normalizing 
normalize=(data-mean)/std_dev
print(normalize)

3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
